spring:
  datasource:
    url: jdbc:mysql://localhost:3306/astrotalk?createDatabaseIfNotExist=true
    username: root
    password: subham123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQLDialect

